Revert "2025y-06m-11d-07h-28m-11s UTC: drm-tip rerere cache update"
This reverts commit 2d6b93eda1d63812509ee6a93600840f5b5cc5fc.

The conflict resolution in the merge is incorrect and results in
the following build error.

drivers/gpu/drm/vc4/vc4_hdmi.c: In function ‘vc4_hdmi_audio_init’:
drivers/gpu/drm/vc4/vc4_hdmi.c:2294:15: error: too few arguments to function ‘drm_connector_hdmi_audio_init’
 2294 |         ret = drm_connector_hdmi_audio_init(&vc4_hdmi->connector, dev,
      |               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from drivers/gpu/drm/vc4/vc4_hdmi.c:34:
include/drm/display/drm_hdmi_audio_helper.h:13:5: note: declared here
   13 | int drm_connector_hdmi_audio_init(struct drm_connector *connector,
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~